
name: IDMC - Promote Single Commit from Dev to QA

on:
  push:
    branches:
      - dev
    tags:
      - 'Jira-*'   # Only run when a tag starting with "qa-" is created on a dev commit

jobs:
  promote:
    name: Cherry-pick Tagged Commit into QA and Trigger Informatica
    runs-on: ubuntu-latest
    environment: IDMC-QA

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch full history for cherry-pick

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Cherry-pick tagged commit into QA
        run: |
          git fetch origin dev
          git fetch origin qa

          git checkout qa
          git cherry-pick -X theirs $GITHUB_SHA || true
          git push origin qa

     
