
name: IDMC - Promote Single Commit from Dev to QA

on:
  push:
    branches:
      - dev
    tags:
      - 'Jira-*'   # Only run when a tag starting with "qa-" is created on a dev commit

jobs:
  promote:
    name: Cherry-pick Tagged Commit into QA and Trigger Informatica
    runs-on: ubuntu-latest
    environment: IDMC-QA

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch full history for cherry-pick

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Cherry-pick tagged commit into QA
        run: |
          git fetch origin dev
          git fetch origin qa

          git checkout qa
          git cherry-pick -X theirs $GITHUB_SHA || true
          git push origin qa

      - name: Authenticate with Infa Cloud
        id: infa_auth
        run: |
          echo "Authenticating with Informatica Cloud..."
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -d '{
                  "username": "${{ secrets.IDMC_USER }}",
                  "password": "${{ secrets.IDMC_PASS }}"
                }' \
            https://dm-us.informaticacloud.com/saas/public/core/v3/login)

          echo "Full response: $RESPONSE"
          SESSION_ID=$(echo $RESPONSE | jq -r '.userInfo.icSessionId')
          echo $SESSION_ID
          if [ "$SESSION_ID" = "null" ] || [ -z "$SESSION_ID" ]; then
            echo "Authentication failed"
            exit 1
          fi
          echo "SESSION_ID=$SESSION_ID" >> $GITHUB_ENV
          
          INFA_API_URL=$(echo $RESPONSE | jq -r '.products[0].baseApiUrl')
          echo "INFA_API_URL=$INFA_API_URL" >> $GITHUB_ENV

      - name: Pull into Infa Cloud
        id: infa_pull_by_hash
        run: |
          echo "Pulling code into Infa Cloud..."
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -d '{
                  "commitHash": "$GITHUB_SHA",
                  "searchCustomRepositories": true
                }' \
            $INFA_API_URL/public/core/v3/pullByCommitHash
            )

          echo "Full response: $RESPONSE"
          INFA_PULL_ID=$(echo $RESPONSE | jq -r '.pullActionId')
